### PR TITLE
Integration with Sonar (proper pull request)

### PR DESCRIPTION
**Pull request by bsodzik**
I messed pull request https://github.com/futurice/mocha-jenkins-reporter/pull/17 so I had to create new one. Added some documentation and changed the way of replacing `.js` file extension.

### CODE REVIEW

**Comment by jvah** [comment]
I'll merge this first and make a release, thank you.

**Comment by bsodzik** [comment]
Thank you as well :)

**Comment by jvah** [comment]
Please make sure version 0.1.5 works for you.

**Comment by mendlik** [comment]
I've just tested it in my project, works great. Thank you both :)

**Pull request merged**
